#!/bin/bash 
#This is the analysis pipeline for all subjects and all runs. Requires one exemplar of each analysis to reference. 
##FOR SERVER
##COMMENT OUT QSUB TO TEST

j=(001 002 003 004)
INDEX="1 2 3 4"

######################
######SMOOTHED
######################

######
#GAP
######
count=0
for i in $INDEX; do
for r in 1 2 3 4 5 6 7; do

cat /psyhome/u7/tayjonat/gapclass/york/analysis/smoothed/001/gap1.feat/design.fsf | sed "s/001/${j[$count]}/g" | sed "s/gap1/gap${r}/g" > /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_gap${r}_analysis_smoothed.fsf;

echo "Created analysis .fsf file for subject ${j[$count]} gap${r}!"
echo "/usr/lib/fsl/5.0/feat /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_gap${r}_analysis_smoothed.fsf" > tmpscript

qsub -q all.q tmpscript;

done
((count++))
done


######
#IMAGINE
######
count=0
for i in $INDEX; do
for r in 1 2; do

cat /psyhome/u7/tayjonat/gapclass/york/analysis/smoothed/001/imagine1.feat/design.fsf | sed "s/001/${j[$count]}/g" | sed "s/imagine1/imagine${r}/g" > /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_imagine${r}_analysis_smoothed.fsf;

echo "Created analysis .fsf file for subject ${j[$count]} imagine${r}!"
echo "/usr/lib/fsl/5.0/feat /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_imagine${r}_analysis_smoothed.fsf" > tmpscript

qsub -q all.q tmpscript;

done
((count++))
done


######
#LOC
######
count=0
for i in $INDEX; do
for r in 1 2; do

cat /psyhome/u7/tayjonat/gapclass/york/analysis/smoothed/001/loc1.feat/design.fsf | sed "s/001/${j[$count]}/g" | sed "s/loc1/loc${r}/g" > /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_loc${r}_analysis_smoothed.fsf;

echo "Created analysis .fsf file for subject ${j[$count]} loc${r}!"
echo "/usr/lib/fsl/5.0/feat /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_loc${r}_analysis_smoothed.fsf" > tmpscript

qsub -q all.q tmpscript;

done
((count++))
done


######################
######UNSMOOTHED
######################


######
#GAP
######
count=0
for i in $INDEX; do
for r in 1 2 3 4 5 6 7; do

cat /psyhome/u7/tayjonat/gapclass/york/analysis/unsmoothed/001/gap1.feat/design.fsf | sed "s/001/${j[$count]}/g" | sed "s/gap1/gap${r}/g" > /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_gap${r}_analysis_smoothed.fsf;

echo "Created analysis .fsf file for subject ${j[$count]} gap${r}!"
echo "/usr/lib/fsl/5.0/feat /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_gap${r}_analysis_smoothed.fsf" > tmpscript

qsub -q all.q tmpscript;

done
((count++))
done


######
#IMAGINE
######
count=0
for i in $INDEX; do
for r in 1 2; do

cat /psyhome/u7/tayjonat/gapclass/york/analysis/unsmoothed/001/imagine1.feat/design.fsf | sed "s/001/${j[$count]}/g" | sed "s/imagine1/imagine${r}/g" > /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_imagine${r}_analysis_smoothed.fsf;

echo "Created analysis .fsf file for subject ${j[$count]} imagine${r}!"
echo "/usr/lib/fsl/5.0/feat /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_imagine${r}_analysis_smoothed.fsf" > tmpscript

qsub -q all.q tmpscript;

done
((count++))
done
