#!/bin/bash 
#This creates masks for partial FOV functional data, in order to pass fieldmaps through. 
#No preprocessing except BET and highpass filter. Must be done on RAW data.

j=(001 002 003 004)
INDEX="1 2 3 4"

######
#GAP
######
count=0
for i in $INDEX; do
for r in 1 2 3 4 5 6 7; do

cat /psyhome/u7/tayjonat/gapclass/york/partialFOVmasks_for_fieldmap/001/gap1.feat/design.fsf | sed "s/001/${j[$count]}/g" | sed "s/gap1/gap${r}/g" > /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_gap${r}_partialFOVmask.fsf;

echo "Created preproc .fsf file for partial FOV mask for subject ${j[$count]} gap${r}!"
echo "/usr/lib/fsl/5.0/feat /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_gap${r}_partialFOVmask.fsf" > tmpscript

qsub -q all.q tmpscript;

done
((count++))
done

######
#IMAGINE
######
#count=0
#for i in $INDEX; do
#for r in 1 2; do

#cat /psyhome/u7/tayjonat/gapclass/york/preproc/smoothed/001/imagine1.feat/design.fsf | sed "s/001/${j[$count]}/g" | sed "s/imagine1/imagine${r}/g" > /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_imagine${r}_smoothed.fsf;

#echo "Created preproc .fsf file for subject ${j[$count]} imagine${r}!"
#echo "/usr/lib/fsl/5.0/feat /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_imagine${r}_smoothed.fsf" > tmpscript

#qsub -q all.q tmpscript;

#done
#((count++))
#done


######
#LOC
######
#count=0
#for i in $INDEX; do
#for r in 1 2; do

#cat /psyhome/u7/tayjonat/gapclass/york/preproc/smoothed/001/loc1.feat/design.fsf | sed "s/001/${j[$count]}/g" | sed "s/loc1/loc${r}/g" > /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_loc${r}_smoothed.fsf;

#echo "Created preproc .fsf file for subject ${j[$count]} loc${r}!"
#echo "/usr/lib/fsl/5.0/feat /psyhome/u7/tayjonat/gapclass/york/fsf_files/${j[$count]}_loc${r}_smoothed.fsf" > tmpscript

#qsub -q all.q tmpscript;

#done
#((count++))
#done
