#!/bin/bash 
#This is the full analysis pipeline for all subjects and all runs. Requires one exemplar of each analysis to reference. 
##FOR LAB MACS


######################
######SMOOTHED
######################

######
#GAP
######
count=0
for r in 2 3 4 5 6 7 8 9; do

cat /Users/labuser/Documents/Jonathan_gapclass/highres_data/york/full_analysis/smoothed/all_gap/contrast1.gfeat/design.fsf | sed "s/cope1.feat/cope${r}.feat/g" | sed "s/contrast1/contrast${r}/" > /Users/labuser/Documents/Jonathan_gapclass/highres_data/york/fsf_files/grouplevel_gap_contrast${r}_smoothed.fsf;

echo "Created full analysis .fsf file for gap cope${r}!"

done
((count++))


######
#IMAGINE
######
count=0
for r in 2 3 4 5 6 7 8 9; do

cat /Users/labuser/Documents/Jonathan_gapclass/highres_data/york/full_analysis/smoothed/all_imagine/contrast1.gfeat/design.fsf | sed "s/cope1.feat/cope${r}.feat/g" | sed "s/contrast1/contrast${r}/" > /Users/labuser/Documents/Jonathan_gapclass/highres_data/york/fsf_files/grouplevel_imagine_contrast${r}_smoothed.fsf;

echo "Created full analysis .fsf file for imagine cope${r}!"

done
((count++))


######
#LOC
######
count=0
for r in 2 3 4 5 6 7 8 9; do

cat /Users/labuser/Documents/Jonathan_gapclass/highres_data/york/full_analysis/smoothed/all_loc/contrast1.gfeat/design.fsf | sed "s/cope1.feat/cope${r}.feat/g" | sed "s/contrast1/contrast${r}/" > /Users/labuser/Documents/Jonathan_gapclass/highres_data/york/fsf_files/grouplevel_loc_contrast${r}_smoothed.fsf;

echo "Created full analysis .fsf file for loc cope${r}!"

done
((count++))
